export const outputNames = [
  'Full-range',
  'Subwoofer',
  'Low',
  'Low-mid',
  'Mid',
  'Hi-mid',
  'Hi',
  'Left Full-range',
  'Left Subwoofer',
  'Left Low',
  'Left Low-mid',
  'Left Mid',
  'Left Hi-mid',
  'Left Hi',
  'Right Full-range',
  'Right Subwoofer',
  'Right Low',
  'Right Low-mid',
  'Right Mid',
  'Right Hi-mid',
  'Right Hi',
  'Center Full-range',
  'Center Subwoofer',
  'Center Low',
  'Center Low-mid',
  'Center Mid',
  'Center Hi-mid',
  'Center Hi',
];
