
import { SerialPort } from 'serialport';
import * as fs from 'fs';
import {
    extractSysexMessages,
    parseMessage,
} from './src/index.js';
import { RestoreSession } from './src/restore.js';

const SERIAL_PORT = process.env.DCX_PORT || '/dev/cu.usbserial-1430';
const BAUDRATE = 38400;

function sleep(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
    const dcxPath = process.argv[2] || 'current.dcx';

    if (!fs.existsSync(dcxPath)) {
        console.error(`ERROR: DCX file not found: ${dcxPath}`);
        process.exit(1);
    }

    console.log('=== DCX Device Upload (Pull Protocol) ===\n');

    // Read DCX file
    const dcxData = new Uint8Array(fs.readFileSync(dcxPath));
    console.log(`Loaded ${dcxPath}: ${dcxData.length} bytes`);

    // Create restore session
    const session = new RestoreSession(dcxData);
    const status = session.getStatus();
    console.log(`Prepared upload session. Phase: ${status.phase}\n`);

    // Open serial port
    console.log(`Opening serial port ${SERIAL_PORT}...`);
    const port = new SerialPort({ path: SERIAL_PORT, baudRate: BAUDRATE });

    // Wait for open
    await new Promise<void>((resolve, reject) => {
        port.on('open', () => resolve());
        port.on('error', reject);
    });
    console.log('Port opened.\n');

    // Flush buffer
    console.log('Flushing buffer...');
    port.flush();
    await sleep(200);

    // Buffer for incoming data
    let incomingBuffer = new Uint8Array(0);

    // Helper to send queue
    const processQueue = async () => {
        let msg = session.getNextMessage();
        while (msg) {
            console.log(`Creating/Sending packet (${msg.length} bytes)...`);
            port.write(msg);
            port.drain(); // Wait for write to complete
            // Small delay to prevent flooding?
            await sleep(50);
            msg = session.getNextMessage();
        }
    };

    // Data handler
    port.on('data', async (data: Buffer) => {
        // Append to buffer using generic typed array concatenation because Buffer and Uint8Array types can conflict
        const newBuffer = new Uint8Array(incomingBuffer.length + data.length);
        newBuffer.set(incomingBuffer);
        newBuffer.set(data, incomingBuffer.length);
        incomingBuffer = newBuffer;

        const { messages, remaining } = extractSysexMessages(incomingBuffer);
        incomingBuffer = remaining;

        for (const msgBytes of messages) {
            const parsed = parseMessage(msgBytes);
            if (parsed) {
                if (parsed.type === 'pageRequest') {
                    console.log(`DEV -> APP: Page Request (Page: ${parsed.page}, Type: ${parsed.requestType})`);
                } else if (parsed.type === 'unknown') {
                    // console.log(`DEV -> APP: Unknown (${msgBytes.length} bytes)`);
                } else {
                    console.log(`DEV -> APP: ${parsed.type}`);
                }

                // Feed to session
                session.processResponse(parsed);

                // Check status
                if (session.isComplete()) {
                    console.log('\n=== Upload Complete! ===');
                    process.exit(0);
                }

                // Process any new outgoing messages generated by the response
                await processQueue();
            }
        }
    });

    // START
    console.log('Starting session...');
    session.start();
    await processQueue();

    // Keep alive loop with status monitor
    setInterval(() => {
        const s = session.getStatus();
        // console.log(`Status: ${s.phase}, Queue: ${s.queueLength}`);
        if (s.phase === 'ERROR') {
            console.error('Session Error!');
            process.exit(1);
        }
    }, 1000);
}

main().catch(console.error);
